openapi: 3.1.0
info:
  title: Habit Hero API
  version: 1.3.0
  description: |
    A/B course contract for Lesson 4.
    Adds lifecycle commands, bulk command execution, and user audit events.
servers:
  - url: http://localhost:8080
paths:
  /health:
    get:
      summary: Healthcheck
      operationId: healthcheck
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /api/v1/users:
    post:
      summary: Register user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    get:
      summary: List users
      operationId: listUsers
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PerPage'
        - $ref: '#/components/parameters/EmailContains'
        - $ref: '#/components/parameters/Active'
        - $ref: '#/components/parameters/UserSortBy'
        - $ref: '#/components/parameters/SortOrder'
      responses:
        '200':
          description: Paged users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUsersResponse'
        '400':
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/v1/users/{id}:
    get:
      summary: Get user by id
      operationId: getUser
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: User by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    patch:
      summary: Update user
      operationId: updateUser
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/IfMatchVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: Updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    delete:
      summary: Delete user
      operationId: deleteUser
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/IfMatchVersion'
      responses:
        '204':
          description: Deleted
        '400':
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/v1/users/{id}/commands:
    post:
      summary: Apply lifecycle command for one user
      operationId: applyUserLifecycleCommand
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/IfMatchVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplyUserCommandRequest'
      responses:
        '200':
          description: Updated user after command
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/v1/users/commands/bulk-lifecycle:
    post:
      summary: Apply lifecycle command to many users
      operationId: bulkApplyUserLifecycleCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkLifecycleCommandRequest'
      responses:
        '200':
          description: Bulk command summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkLifecycleCommandResponse'
        '400':
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/v1/users/{id}/events:
    get:
      summary: List user audit events
      operationId: listUserEvents
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/EventsLimit'
      responses:
        '200':
          description: User events list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEventsResponse'
        '400':
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  parameters:
    UserId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
    IfMatchVersion:
      name: If-Match
      in: header
      required: true
      schema:
        type: string
      description: Expected current entity version as positive integer.
    EventsLimit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
    PerPage:
      name: per_page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
    EmailContains:
      name: email_contains
      in: query
      required: false
      schema:
        type: string
    Active:
      name: active
      in: query
      required: false
      schema:
        type: boolean
    UserSortBy:
      name: sort_by
      in: query
      required: false
      schema:
        type: string
        enum: [created_at, email, display_name]
        default: created_at
    SortOrder:
      name: order
      in: query
      required: false
      schema:
        type: string
        enum: [asc, desc]
        default: desc
  schemas:
    CreateUserRequest:
      type: object
      additionalProperties: false
      required: [email, display_name]
      properties:
        email:
          type: string
          format: email
          maxLength: 320
        display_name:
          type: string
          minLength: 1
          maxLength: 100
    UpdateUserRequest:
      type: object
      additionalProperties: false
      properties:
        display_name:
          type: string
          minLength: 1
          maxLength: 100
        active:
          type: boolean
      minProperties: 1
    UserLifecycleCommand:
      type: string
      enum: [activate, deactivate]
    ApplyUserCommandRequest:
      type: object
      additionalProperties: false
      required: [command]
      properties:
        command:
          $ref: '#/components/schemas/UserLifecycleCommand'
    BulkLifecycleCommandRequest:
      type: object
      additionalProperties: false
      required: [ids, command]
      properties:
        ids:
          type: array
          minItems: 1
          maxItems: 1000
          items:
            type: string
            format: uuid
        command:
          $ref: '#/components/schemas/UserLifecycleCommand'
    BulkLifecycleCommandResponse:
      type: object
      additionalProperties: false
      required: [requested, processed, command]
      properties:
        requested:
          type: integer
          format: int64
        processed:
          type: integer
          format: int64
        command:
          $ref: '#/components/schemas/UserLifecycleCommand'
    UserAuditEventResponse:
      type: object
      additionalProperties: false
      required: [id, user_id, event_type, message, resulting_version, created_at]
      properties:
        id:
          type: string
        user_id:
          type: string
          format: uuid
        event_type:
          type: string
        message:
          type: string
        resulting_version:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
    UserEventsResponse:
      type: object
      additionalProperties: false
      required: [items, limit]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/UserAuditEventResponse'
        limit:
          type: integer
          format: int32
    UserResponse:
      type: object
      additionalProperties: false
      required:
        - id
        - email
        - display_name
        - active
        - version
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        display_name:
          type: string
        active:
          type: boolean
        version:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    PaginatedUsersResponse:
      type: object
      additionalProperties: false
      required: [items, page, per_page, total, total_pages]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
        page:
          type: integer
          format: int32
        per_page:
          type: integer
          format: int32
        total:
          type: integer
          format: int64
        total_pages:
          type: integer
          format: int32
    ProblemDetails:
      type: object
      additionalProperties: false
      required: [type, title, status, detail, correlation_id]
      properties:
        type:
          type: string
          format: uri-reference
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        correlation_id:
          type: string
    HealthResponse:
      type: object
      additionalProperties: false
      required: [status]
      properties:
        status:
          type: string
          enum: [ok]
