#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLASSIC_SRC="${ROOT_DIR}/education/habit-hero-ab/lesson4/classic-api/src"
PRODUCT_SRC="${ROOT_DIR}/education/habit-hero-ab/lesson4/product-api/src"
CLASSIC_APP="${CLASSIC_SRC}/application"
PRODUCT_APP="${PRODUCT_SRC}/application"
METRICS_OUT="${ROOT_DIR}/llm/BASELINE_AUTONOMY_METRICS.md"
RUN_GATES=0

if [[ $# -gt 1 ]]; then
  echo "Usage: $0 [--run-gates]" >&2
  exit 2
fi

if [[ $# -eq 1 ]]; then
  if [[ "$1" != "--run-gates" ]]; then
    echo "Usage: $0 [--run-gates]" >&2
    exit 2
  fi
  RUN_GATES=1
fi

# Keep pattern aligned with guard_lesson4_no_persistence_leak.sh
PERSISTENCE_LEAK_PATTERN='snapshot_for_external_transaction|restore_snapshot_for_external_transaction|shared_session|on_external_mutation_committed|PersistSession|_with_session\(|_with_tx\(|open_user_workspace_store|UserWorkspaceStore|PersistUserStore|Repository'

count_rs_files() {
  local dir="$1"
  if [[ ! -d "${dir}" ]]; then
    echo "0"
    return
  fi
  find "${dir}" -type f -name '*.rs' | awk 'END { print NR + 0 }'
}

count_rs_loc() {
  local dir="$1"
  if [[ ! -d "${dir}" ]]; then
    echo "0"
    return
  fi

  local sum=0
  while IFS= read -r file; do
    local lines
    lines="$(wc -l < "${file}")"
    sum=$((sum + lines))
  done < <(find "${dir}" -type f -name '*.rs' | sort)

  echo "${sum}"
}

count_pattern_hits() {
  local pattern="$1"
  local dir="$2"
  if [[ ! -d "${dir}" ]]; then
    echo "0"
    return
  fi

  local matches
  matches="$(rg -n "${pattern}" "${dir}" 2>/dev/null || true)"
  if [[ -z "${matches}" ]]; then
    echo "0"
    return
  fi
  printf '%s\n' "${matches}" | wc -l | awk '{ print $1 + 0 }'
}

pct_change() {
  local from="$1"
  local to="$2"
  awk -v from="${from}" -v to="${to}" 'BEGIN {
    if (from == 0) { print "0.00"; exit 0; }
    printf "%.2f", ((to - from) * 100.0) / from
  }'
}

classic_total_loc="$(count_rs_loc "${CLASSIC_SRC}")"
product_total_loc="$(count_rs_loc "${PRODUCT_SRC}")"
classic_total_files="$(count_rs_files "${CLASSIC_SRC}")"
product_total_files="$(count_rs_files "${PRODUCT_SRC}")"

classic_application_loc="$(count_rs_loc "${CLASSIC_APP}")"
product_application_loc="$(count_rs_loc "${PRODUCT_APP}")"
classic_application_files="$(count_rs_files "${CLASSIC_APP}")"
product_application_files="$(count_rs_files "${PRODUCT_APP}")"

classic_infra_loc="$(count_rs_loc "${CLASSIC_SRC}/infrastructure")"
product_infra_loc="$(count_rs_loc "${PRODUCT_SRC}/infrastructure")"
classic_infra_files="$(count_rs_files "${CLASSIC_SRC}/infrastructure")"
product_infra_files="$(count_rs_files "${PRODUCT_SRC}/infrastructure")"

classic_red_flags="$(count_pattern_hits "${PERSISTENCE_LEAK_PATTERN}" "${CLASSIC_APP}")"
product_red_flags="$(count_pattern_hits "${PERSISTENCE_LEAK_PATTERN}" "${PRODUCT_APP}")"

if [[ -f "${PRODUCT_APP}/user_workspace_store.rs" ]]; then
  product_adapter_file_present="yes"
else
  product_adapter_file_present="no"
fi

net_loc_delta=$((product_total_loc - classic_total_loc))
net_file_delta=$((product_total_files - classic_total_files))
infra_loc_removed=$((classic_infra_loc - product_infra_loc))
infra_files_removed=$((classic_infra_files - product_infra_files))
red_flag_delta=$((product_red_flags - classic_red_flags))

total_loc_pct="$(pct_change "${classic_total_loc}" "${product_total_loc}")"
app_loc_pct="$(pct_change "${classic_application_loc}" "${product_application_loc}")"
infra_loc_pct="$(pct_change "${classic_infra_loc}" "${product_infra_loc}")"

generated_at_utc="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"

gate_guard="NOT RUN"
gate_stress="NOT RUN"
gate_app="NOT RUN"
gate_lesson4="NOT RUN"
gates_executed="no"
gate_failed=0

if [[ "${RUN_GATES}" -eq 1 ]]; then
  gates_executed="yes"

  if "${ROOT_DIR}/scripts/guard_lesson4_no_persistence_leak.sh" >/dev/null; then
    gate_guard="PASS"
  else
    gate_guard="FAIL"
    gate_failed=1
  fi

  if (cd "${ROOT_DIR}" && cargo test --test persist_app_stress_tests >/dev/null); then
    gate_stress="PASS"
  else
    gate_stress="FAIL"
    gate_failed=1
  fi

  if (cd "${ROOT_DIR}" && cargo test --test persist_app_tests >/dev/null); then
    gate_app="PASS"
  else
    gate_app="FAIL"
    gate_failed=1
  fi

  if (cd "${ROOT_DIR}" && cargo test --manifest-path education/habit-hero-ab/lesson4/product-api/Cargo.toml >/dev/null); then
    gate_lesson4="PASS"
  else
    gate_lesson4="FAIL"
    gate_failed=1
  fi
fi

cat > "${METRICS_OUT}" <<EOF
# Baseline Autonomy Metrics

Status: ACTIVE  
Generated At (UTC): ${generated_at_utc}  
Generated By: \`scripts/collect_autonomy_metrics.sh\`

## Scope

- Classic reference: \`education/habit-hero-ab/lesson4/classic-api/src\`
- Product reference: \`education/habit-hero-ab/lesson4/product-api/src\`
- Part B app-layer gate scope: \`education/habit-hero-ab/lesson4/product-api/src/application\`

## Boilerplate Delta (Classic -> Product)

| Metric | Classic | Product | Delta |
|---|---:|---:|---:|
| Total Rust LOC | ${classic_total_loc} | ${product_total_loc} | ${net_loc_delta} (${total_loc_pct}%) |
| Total Rust files | ${classic_total_files} | ${product_total_files} | ${net_file_delta} |
| Application LOC | ${classic_application_loc} | ${product_application_loc} | $((product_application_loc - classic_application_loc)) (${app_loc_pct}%) |
| Application files | ${classic_application_files} | ${product_application_files} | $((product_application_files - classic_application_files)) |
| Infrastructure LOC | ${classic_infra_loc} | ${product_infra_loc} | -${infra_loc_removed} (${infra_loc_pct}%) |
| Infrastructure files | ${classic_infra_files} | ${product_infra_files} | -${infra_files_removed} |

Interpretation:
- Infrastructure/repository boilerplate category is removed from Part B (\`infrastructure\` LOC/files reduced to zero).
- Product app shifts complexity into domain-intent/workspace surface while deleting storage-layer classes.

## AUTONOMY_DX_CONTRACT Red-Flag Delta

Pattern:
\`${PERSISTENCE_LEAK_PATTERN}\`

| Scope | Hits |
|---|---:|
| Classic app layer | ${classic_red_flags} |
| Product app layer | ${product_red_flags} |
| Delta (product - classic) | ${red_flag_delta} |

Additional checks:
- \`product-api/src/application/user_workspace_store.rs\` present: **${product_adapter_file_present}**

## Conflict Semantics Parity (Evidence)

- Policy retry scope: only transient \`write_write\` conflicts.
- Business stale \`If-Match\`: \`optimistic_lock\` is not auto-retried.
- Unique constraint semantics remain explicit conflict class.

Evidence tests:
- \`tests/persist_app_tests.rs::persist_app_transaction_retries_write_write_conflict_via_policy\`
- \`tests/persist_app_tests.rs::persist_app_transaction_does_not_retry_optimistic_lock_conflicts\`
- \`tests/persist_app_stress_tests.rs::write_write_retry_disabled_conflicts_surface\`
- \`tests/persist_app_stress_tests.rs::write_write_retry_enabled_eventual_success\`
- \`tests/persist_app_stress_tests.rs::optimistic_lock_is_not_retried_under_load\`

## Rollback Correctness (Evidence)

- No partial writes under repeated \`atomic_with\` failures.
- Rollback then replay keeps version and audit history consistent.

Evidence tests:
- \`tests/persist_app_stress_tests.rs::atomic_with_repeated_failures_has_no_partial_writes\`
- \`tests/persist_app_stress_tests.rs::rollback_then_replay_keeps_consistent_versions\`
- \`education/habit-hero-ab/lesson4/product-api/src/application/user_workspace.rs::lifecycle_failpoint_rolls_back_user_and_audit_event\`

## Mandatory Gate Commands

\`\`\`bash
scripts/guard_lesson4_no_persistence_leak.sh
cargo test --test persist_app_stress_tests
cargo test --test persist_app_tests
cargo test --manifest-path education/habit-hero-ab/lesson4/product-api/Cargo.toml
\`\`\`

## Gate Results

- Gates executed during report generation: **${gates_executed}**
- guard_lesson4_no_persistence_leak: **${gate_guard}**
- persist_app_stress_tests: **${gate_stress}**
- persist_app_tests: **${gate_app}**
- lesson4_product_api_suite: **${gate_lesson4}**

## Guidance

1. Keep retry policy under \`PersistAppPolicy::conflict_retry\`; do not add retry loops in handlers/services.
2. Treat any new Part B adapter/repository/store layer as a contract break unless it deletes more persistence thinking than it introduces.
3. Use this report as a release gate artifact for lesson updates.
EOF

echo "Autonomy metrics written to: ${METRICS_OUT}"

if [[ "${gate_failed}" -ne 0 ]]; then
  exit 1
fi
